# Generated by Django 5.0.7 on 2026-08-08 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_technology_remove_project_tech_stack_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Font Awesome icon class", max_length=50
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                (
                    "start_date",
                    models.CharField(help_text="e.g. 2024 - Present", max_length=50),
                ),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Education",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=200)),
                ("company", models.CharField(blank=True, max_length=200)),
                (
                    "start_date",
                    models.CharField(help_text="e.g. 2024 - Present", max_length=50),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tech tags",
                        max_length=300,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Experiences",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Bhupesh Dewangan", max_length=100)),
                (
                    "title",
                    models.CharField(
                        default="Python & Django Developer", max_length=200
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                ("about_text", models.TextField(blank=True)),
                (
                    "email",
                    models.EmailField(default="bhupeshdeww@gmail.com", max_length=254),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "location",
                    models.CharField(default="Chhattisgarh, India", max_length=100),
                ),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("available", models.BooleanField(default=True)),
                (
                    "available_text",
                    models.CharField(default="Available for work", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("backend", "Backend"),
                            ("frontend", "Frontend"),
                            ("database", "Databases"),
                            ("tools", "Tools"),
                        ],
                        default="backend",
                        max_length=50,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Font Awesome icon class", max_length=50
                    ),
                ),
                (
                    "percentage",
                    models.IntegerField(
                        default=80,
                        help_text="Skill proficiency percentage",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Lower = appears first"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={"ordering": ["-sent_at"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="technology",
            options={"ordering": ["name"], "verbose_name_plural": "Technologies"},
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="technology",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Font Awesome icon class (e.g. fab fa-python)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Pin to featured section on home page"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Project banner/cover image",
                null=True,
                upload_to="projects/",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="main.technology"
            ),
        ),
    ]
