# Generated by Django 6.0.2 on 2026-08-11 18:37

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_achievement_education_experience_profile_skill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="file",
            field=models.FileField(
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="resumes/",
            ),
        ),
    ]
